export interface AnimalCrossingData {
    // "57910070": N57910070[];
    // "174648279": N174648279[];
    // "438678619": N438678619[];
    // "476332365": N476332365[];
    // "938009211": N938009211[];
    Equipment: Equipment[];
    Housewares: Housewares[];
    Rugs: Rugs[];
    Wallpaper: Wallpaper[];
    Miscellaneous: Miscellaneous[];
    Tools: Tools[];
    Floors: Floors[];
    Other: Other[];
    "Wall-mounted": WallMounted[];
    "Dress-Up": DressUp[];
  }
  
  export interface N57910070 {
    Name: string;
    Image: string;
    Variation: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    DIY: string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Buy: string;
    Sell: string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Surface: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "HHA Base Points": string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "Variant ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    Customize: string;
  }
  
  export interface N174648279 {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Label Themes": string;
    "Sort Order": string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Miles Price": string;
    Type: string;
    Image: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Surface: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Variant ID": string;
    Customize: string;
  }
  
  export interface N438678619 {
    Name: string;
    Image: string;
    Variation: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    DIY: string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Buy: string;
    Sell: string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Surface: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "HHA Base Points": string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "Variant ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    Customize: string;
    "Closet Image": string;
    "Storage Image": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Label Themes": string;
    "Sort Order": string;
    "Villager Equippable": string;
    "ClothGroup ID": string;
  }
  
  export interface N476332365 {
    Name: string;
    Image: string;
    Variation: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    DIY: string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Buy: string;
    Sell: string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Surface: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "HHA Base Points": string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "Variant ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
  }
  
  export interface N938009211 {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Label Themes": string;
    "Sort Order": string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    Image: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Surface: string;
    "Miles Price": string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Variant ID": string;
    Customize: string;
  }
  
  export interface Equipment {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Housewares {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Rugs {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Wallpaper {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Miscellaneous {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Tools {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Floors {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Stack Size": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface Other {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    "Stack Size": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface WallMounted {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    "Miles Price": string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Sort Order": string;
    "Label Themes": string;
    Type: string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Achievement Description": string;
    "Achievement Criteria": string;
    "#": string;
    "Internal Name": string;
    "Internal Category": string;
    "Num of Tiers": string;
    "Tier 1": string;
    "Tier 2": string;
    "Tier 3": string;
    "Tier 4": string;
    "Tier 5": string;
    "Tier 6": string;
    "Tier 1 Reward": string;
    "Tier 2 Reward": string;
    "Tier 3 Reward": string;
    "Tier 4 Reward": string;
    "Tier 5 Reward": string;
    "Tier 6 Reward": string;
    "Tier 1 Modifier": string;
    "Tier 1 Noun": string;
    "Tier 2 Modifier": string;
    "Tier 2 Noun": string;
    "Tier 3 Modifier": string;
    "Tier 3 Noun": string;
    "Tier 4 Modifier": string;
    "Tier 4 Noun": string;
    "Tier 5 Modifier": string;
    "Tier 5 Noun": string;
    "Tier 6 Modifier": string;
    "Tier 6 Noun": string;
    Sequential: string;
    Image: string;
    "High-Res Texture": string;
    Genuine: string;
    Category: string;
    "Real Artwork Title": string;
    Artist: string;
    Description: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    Interact: string;
    Tag: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    _id: string;
    "Icon Image": string;
    "Critterpedia Image": string;
    "Furniture Image": string;
    "Where/How": string;
    Shadow: string;
    "Catch Difficulty": string;
    Vision: string;
    "Total Catches to Unlock": string;
    "Spawn Rates": string;
    "NH Jan": string;
    "NH Feb": string;
    "NH Mar": string;
    "NH Apr": string;
    "NH May": string;
    "NH Jun": string;
    "NH Jul": string;
    "NH Aug": string;
    "NH Sep": string;
    "NH Oct": string;
    "NH Nov": string;
    "NH Dec": string;
    "SH Jan": string;
    "SH Feb": string;
    "SH Mar": string;
    "SH Apr": string;
    "SH May": string;
    "SH Jun": string;
    "SH Jul": string;
    "SH Aug": string;
    "SH Sep": string;
    "SH Oct": string;
    "SH Nov": string;
    "SH Dec": string;
    Surface: string;
    "Catch phrase": string;
    "HHA Category": string;
    "Icon Filename": string;
    "Critterpedia Filename": string;
    "Furniture Filename": string;
    VFX: string;
    Museum: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Outdoor: string;
    "Variant ID": string;
    Weather: string;
    "Framed Image": string;
    "Album Image": string;
    "Inventory Image": string;
    "Stack Size": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Size Category": string;
    "Movement Speed": string;
    "Photo Image": string;
    Gender: string;
    "Gender (Asia)": string;
    "NPC ID": string;
    Birthday: string;
    Uses: string;
    Set: string;
    "House Image": string;
    Species: string;
    Personality: string;
    Subtype: string;
    Hobby: string;
    Catchphrase: string;
    "Favorite Song": string;
    "Favorite Saying": string;
    "Style 1": string;
    "Style 2": string;
    "Default Clothing": string;
    Wallpaper: string;
    Flooring: string;
    "Furniture List": string;
    "Furniture Name List": string;
    "Door Deco": string;
    "VFX Type": string;
    "Window Type": string;
    "Window Color": string;
    "Pane Type": string;
    "Curtain Type": string;
    "Curtain Color": string;
    "Ceiling Type": string;
  }
  
  export interface DressUp {
    Name: string;
    "Closet Image": string;
    "Storage Image": string;
    Variation: string;
    DIY: string;
    Buy: string;
    Sell: string;
    "HHA Base Points": string;
    "Color 1": string;
    "Color 2": string;
    Size: string;
    Source: string;
    "Source Notes": string;
    "Seasonal Availability": string;
    "Mannequin Piece": string;
    Style: string;
    "Label Themes": string;
    "Sort Order": string;
    "Villager Equippable": string;
    Catalog: string;
    "Version Added": string;
    "Version Unlocked": string;
    Filename: string;
    "ClothGroup ID": string;
    "Internal ID": string;
    "Unique Entry ID": string;
    "Primary Shape": string;
    "Secondary Shape": string;
    "Miles Price": string;
    Type: string;
    Image: string;
    "Body Title": string;
    Pattern: string;
    "Pattern Title": string;
    "Body Customize": string;
    "Pattern Customize": string;
    "Kit Cost": string;
    Surface: string;
    "HHA Concept 1": string;
    "HHA Concept 2": string;
    "HHA Series": string;
    "HHA Set": string;
    "HHA Category": string;
    Interact: string;
    Tag: string;
    Outdoor: string;
    "Speaker Type": string;
    "Lighting Type": string;
    "Variant ID": string;
    Customize: string;
    "#1": string;
    "Material 1": string;
    "#2": string;
    "Material 2": string;
    "#3": string;
    "Material 3": string;
    "#4": string;
    "Material 4": string;
    "#5": string;
    "Material 5": string;
    "#6": string;
    "Material 6": string;
    "Recipes to Unlock": string;
    Category: string;
    "Crafted Item Internal ID": string;
    "Card Color": string;
    "Serial ID": string;
    "Door Deco": string;
  }
  